### ISSUE TITLE
Typings error?

### ISSUE THREAD

**Issue by seriouscoderone** [code0wl/2d-physics-engine#1]
I probably don't understand typescript, but when I do the `typings install` 

```> typings install

typings WARN enoent Path "/Users/jhunsaker/GitHub/2d-physics-engine/lib/typings.json" is missing

└── (No dependencies)

**Comment by code0wl** [comment]
@josephleehunsaker Thanks. I'll update the project. 
I have parked it long enough 👍

**Comment by code0wl** [comment]
@josephleehunsaker I believe I have solved the typings error, I have though only checked running Node on LTS. (v8.9.3) for mac. I'll add Travis for is to check Linux env as well

will work on the weekend to get the demo up and running with some visuals
